import '../models/animal_case.dart';
import '../models/facility.dart';
import '../models/funding_request.dart';
import '../models/donation.dart';
import '../models/medicine.dart';
import '../models/pet_care.dart';
import '../models/adoption.dart';
import '../models/notification.dart';

class MockData {
  static List<Facility> getInitialFacilities() {
    return [
      Facility(
        id: 'fac-01',
        name: 'Paws Veterinary Specialty Hospital',
        type: FacilityType.hospital,
        isVerified: true,
        imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80',
        address: '142 Avinashi Road, Peelamedu',
        city: 'Coimbatore',
        distanceKm: 1.2,
        phone: '+91 98765 43210',
        rating: 4.9,
        openHours: '24/7 Open',
        isOpenNow: true,
        hasEmergency: true,
        offersSupportedCare: true,
        services: ['Emergency Care', 'Surgery', 'X-Ray & Scan', 'ICU Unit', 'Vaccination'],
        totalAnimalsHelped: 1420,
        availableCapacity: 25,
      ),
      Facility(
        id: 'fac-02',
        name: 'Hope Animal Rescue Shelter',
        type: FacilityType.shelter,
        isVerified: true,
        imageUrl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=800&q=80',
        address: '88 Trichy Road, Singanallur',
        city: 'Coimbatore',
        distanceKm: 3.5,
        phone: '+91 98765 43211',
        rating: 4.8,
        openHours: '08:00 AM - 07:00 PM',
        isOpenNow: true,
        hasEmergency: false,
        offersSupportedCare: true,
        services: ['Long-term Shelter', 'Rehabilitation', 'Adoption Drive', 'Foster Care'],
        totalAnimalsHelped: 890,
        availableCapacity: 40,
      ),
      Facility(
        id: 'fac-03',
        name: 'CareVet Clinic & Diagnostic Centre',
        type: FacilityType.clinic,
        isVerified: true,
        imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
        address: '45 Mettupalayam Road',
        city: 'Coimbatore',
        distanceKm: 2.4,
        phone: '+91 98765 43212',
        rating: 4.7,
        openHours: '09:00 AM - 09:00 PM',
        isOpenNow: true,
        hasEmergency: false,
        offersSupportedCare: true,
        services: ['Outpatient Care', 'Lab Diagnostics', 'De-worming', 'Minor Surgery'],
        totalAnimalsHelped: 650,
      ),
      Facility(
        id: 'fac-04',
        name: 'Apex Veterinary Trauma Care',
        type: FacilityType.hospital,
        isVerified: true,
        imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
        address: '12 PN Road',
        city: 'Tiruppur',
        distanceKm: 8.5,
        phone: '+91 98765 43213',
        rating: 4.9,
        openHours: '24/7 Open',
        isOpenNow: true,
        hasEmergency: true,
        offersSupportedCare: true,
        services: ['Trauma Surgery', 'Fracture Repair', 'Blood Bank', 'Ambulance'],
        totalAnimalsHelped: 2100,
      ),
      Facility(
        id: 'fac-05',
        name: 'Karuna Animal Protection Shelter',
        type: FacilityType.shelter,
        isVerified: true,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=800&q=80',
        address: '56 Kangeyam Road',
        city: 'Tiruppur',
        distanceKm: 11.0,
        phone: '+91 98765 43214',
        rating: 4.6,
        openHours: '09:00 AM - 06:00 PM',
        isOpenNow: true,
        hasEmergency: false,
        offersSupportedCare: true,
        services: ['Cattle & Pet Sanctuary', 'Sterilization Drive', 'Adoption'],
        totalAnimalsHelped: 1150,
        availableCapacity: 60,
      ),
      Facility(
        id: 'fac-06',
        name: 'Blue Cross Veterinary Hospital',
        type: FacilityType.hospital,
        isVerified: true,
        imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80',
        address: '22 Velachery Main Road',
        city: 'Chennai',
        distanceKm: 14.2,
        phone: '+91 98765 43215',
        rating: 4.9,
        openHours: '24/7 Open',
        isOpenNow: true,
        hasEmergency: true,
        offersSupportedCare: true,
        services: ['Critical Care', 'ABC Program', 'Oncology', 'Disaster Relief'],
        totalAnimalsHelped: 5400,
      ),
      Facility(
        id: 'fac-07',
        name: 'PetLife Poly Clinic',
        type: FacilityType.clinic,
        isVerified: true,
        imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=800&q=80',
        address: '10 Perundurai Road',
        city: 'Erode',
        distanceKm: 18.0,
        phone: '+91 98765 43216',
        rating: 4.5,
        openHours: '09:30 AM - 08:30 PM',
        isOpenNow: true,
        hasEmergency: false,
        offersSupportedCare: false,
        services: ['Consultation', 'Grooming', 'Vaccination'],
        totalAnimalsHelped: 320,
      ),
      Facility(
        id: 'fac-08',
        name: 'Salem Animal Welfare Sanctuary',
        type: FacilityType.shelter,
        isVerified: true,
        imageUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=800&q=80',
        address: '99 Junction Road',
        city: 'Salem',
        distanceKm: 25.0,
        phone: '+91 98765 43217',
        rating: 4.8,
        openHours: '08:00 AM - 06:00 PM',
        isOpenNow: true,
        hasEmergency: false,
        offersSupportedCare: true,
        services: ['Stray Care', 'Adoption', 'Medical Recovery'],
        totalAnimalsHelped: 980,
        availableCapacity: 35,
      ),
    ];
  }

  static List<AnimalCase> getInitialCases() {
    return [
      AnimalCase(
        id: 'PC-2026-00124',
        animalType: 'Dog',
        condition: 'Critical',
        description: 'Indie dog with leg fracture from hit-and-run accident near Peelamedu signal. Needs emergency surgery.',
        ageGroup: 'Adult',
        locationAddress: 'Avinashi Road, Peelamedu',
        landmark: 'Near PSG College Gate 2',
        volunteerAction: 'I can take the animal to a facility',
        selectedFacilityId: 'fac-01',
        selectedFacilityName: 'Paws Veterinary Specialty Hospital',
        status: CaseStatus.underTreatment,
        reporterName: 'Harsshith Saravanan',
        reporterPhone: '+91 98765 00001',
        imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(hours: 4)),
        estimatedCost: 8000.0,
        pawcareSupport: 5000.0,
        donorSupport: 2000.0,
        remainingCost: 1000.0,
        medicalNotes: [
          'Initial triage completed: Hind leg fracture confirmed via X-Ray.',
          'Fluid therapy started. Scheduled for orthopedic surgery tomorrow morning.',
          'Volunteer Harsshith safely transported the dog.'
        ],
      ),
      AnimalCase(
        id: 'PC-2026-00123',
        animalType: 'Cat',
        condition: 'Injured',
        description: 'Kitten trapped near storm drain with deep paw injury.',
        ageGroup: 'Young',
        locationAddress: 'Trichy Road, Ramanathapuram',
        landmark: 'Behind Alankar Theater',
        volunteerAction: 'I need help finding a facility',
        selectedFacilityId: 'fac-03',
        selectedFacilityName: 'CareVet Clinic & Diagnostic Centre',
        status: CaseStatus.admitted,
        reporterName: 'Priya Sharma',
        reporterPhone: '+91 98765 00002',
        imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(hours: 12)),
        estimatedCost: 3500.0,
        pawcareSupport: 2500.0,
        donorSupport: 1000.0,
        remainingCost: 0.0,
        medicalNotes: ['Wound cleaned and bandaged.', 'Antibiotics course initiated.'],
      ),
      AnimalCase(
        id: 'PC-2026-00122',
        animalType: 'Dog',
        condition: 'Sick',
        description: 'Severe skin allergy and malnutrition. Stray dog living near bus stand.',
        ageGroup: 'Senior',
        locationAddress: 'Gandhipuram Bus Stand',
        landmark: 'Platform 3 Corner',
        volunteerAction: 'I can temporarily care for the animal',
        selectedFacilityId: 'fac-02',
        selectedFacilityName: 'Hope Animal Rescue Shelter',
        status: CaseStatus.fundingReview,
        reporterName: 'Karthik Raja',
        reporterPhone: '+91 98765 00003',
        imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        estimatedCost: 6000.0,
        pawcareSupport: 4000.0,
        donorSupport: 1500.0,
        remainingCost: 500.0,
        medicalNotes: ['Mange treatment started.', 'High-protein diet assigned.'],
      ),
      AnimalCase(
        id: 'PC-2026-00121',
        animalType: 'Puppy',
        condition: 'Abandoned',
        description: 'Litter of 3 puppies abandoned in cardboard box during rain.',
        ageGroup: 'Young',
        locationAddress: 'Saibaba Colony',
        landmark: 'Opposite Ganga Hospital',
        volunteerAction: 'I can temporarily care for the animal',
        selectedFacilityId: 'fac-02',
        selectedFacilityName: 'Hope Animal Rescue Shelter',
        status: CaseStatus.readyForAdoption,
        reporterName: 'Ananya Krishnan',
        reporterPhone: '+91 98765 00004',
        imageUrl: 'https://images.unsplash.com/photo-1591160690555-5debfba289f0?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        estimatedCost: 4000.0,
        pawcareSupport: 4000.0,
        donorSupport: 0.0,
        remainingCost: 0.0,
        medicalNotes: ['De-wormed and first vaccination completed.', 'Healthy and playful.'],
      ),
      AnimalCase(
        id: 'PC-2026-00120',
        animalType: 'Dog',
        condition: 'Injured',
        description: 'Cut injury on tail from barbed wire fence.',
        ageGroup: 'Adult',
        locationAddress: 'PN Road, Tiruppur',
        landmark: 'Near New Bus Stand',
        volunteerAction: 'I can take the animal to a facility',
        selectedFacilityId: 'fac-04',
        selectedFacilityName: 'Apex Veterinary Trauma Care',
        status: CaseStatus.treatmentCompleted,
        reporterName: 'Suresh Kumar',
        reporterPhone: '+91 98765 00005',
        imageUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        estimatedCost: 3000.0,
        pawcareSupport: 2000.0,
        donorSupport: 1000.0,
        remainingCost: 0.0,
        medicalNotes: ['Minor suture performed under local anesthesia.', 'Fully healed.'],
      ),
      AnimalCase(
        id: 'PC-2026-00119',
        animalType: 'Cat',
        condition: 'Sick',
        description: 'Feline viral infection, low energy and dehydration.',
        ageGroup: 'Adult',
        locationAddress: 'Velachery Main Road, Chennai',
        landmark: 'Opposite Grand Mall',
        volunteerAction: 'I need help finding a facility',
        selectedFacilityId: 'fac-06',
        selectedFacilityName: 'Blue Cross Veterinary Hospital',
        status: CaseStatus.adopted,
        reporterName: 'Divya Nair',
        reporterPhone: '+91 98765 00006',
        imageUrl: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        estimatedCost: 5500.0,
        pawcareSupport: 3500.0,
        donorSupport: 2000.0,
        remainingCost: 0.0,
        medicalNotes: ['Recovered completely.', 'Adopted by caring family in Chennai.'],
      ),
      AnimalCase(
        id: 'PC-2026-00118',
        animalType: 'Dog',
        condition: 'Critical',
        description: 'Severe heatstroke and collapse.',
        ageGroup: 'Senior',
        locationAddress: 'Junction Road, Salem',
        landmark: 'Near Railway Station',
        volunteerAction: 'I can take the animal to a facility',
        selectedFacilityId: 'fac-08',
        selectedFacilityName: 'Salem Animal Welfare Sanctuary',
        status: CaseStatus.treatmentCompleted,
        reporterName: 'Venkatesh M',
        reporterPhone: '+91 98765 00007',
        imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        estimatedCost: 4500.0,
        pawcareSupport: 3000.0,
        donorSupport: 1500.0,
        remainingCost: 0.0,
        medicalNotes: ['Cooling protocol administered.', 'Vitals stabilized.'],
      ),
      AnimalCase(
        id: 'PC-2026-00117',
        animalType: 'Puppy',
        condition: 'Healthy',
        description: 'Rescued from high traffic road, needs foster placement.',
        ageGroup: 'Young',
        locationAddress: 'Perundurai Road, Erode',
        landmark: 'Near Collectorate',
        volunteerAction: 'I can temporarily care for the animal',
        selectedFacilityId: 'fac-07',
        selectedFacilityName: 'PetLife Poly Clinic',
        status: CaseStatus.readyForAdoption,
        reporterName: 'Meera R',
        reporterPhone: '+91 98765 00008',
        imageUrl: 'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        estimatedCost: 1500.0,
        pawcareSupport: 1500.0,
        donorSupport: 0.0,
        remainingCost: 0.0,
        medicalNotes: ['Vaccinated and microchipped.'],
      ),
      AnimalCase(
        id: 'PC-2026-00116',
        animalType: 'Cat',
        condition: 'Injured',
        description: 'Eye infection and minor scratches.',
        ageGroup: 'Adult',
        locationAddress: 'Peelamedu, Coimbatore',
        landmark: 'Near Hope College',
        volunteerAction: 'I can take the animal to a facility',
        selectedFacilityId: 'fac-01',
        selectedFacilityName: 'Paws Veterinary Specialty Hospital',
        status: CaseStatus.admitted,
        reporterName: 'Harsshith Saravanan',
        reporterPhone: '+91 98765 00001',
        imageUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(hours: 18)),
        estimatedCost: 2800.0,
        pawcareSupport: 2000.0,
        donorSupport: 800.0,
        remainingCost: 0.0,
        medicalNotes: ['Eye drops prescribed.', 'Bandage applied to paw.'],
      ),
      AnimalCase(
        id: 'PC-2026-00115',
        animalType: 'Dog',
        condition: 'Critical',
        description: 'High fever and parvovirus symptoms.',
        ageGroup: 'Young',
        locationAddress: 'Kangeyam Road, Tiruppur',
        landmark: 'Opposite Government Hospital',
        volunteerAction: 'I need help finding a facility',
        selectedFacilityId: 'fac-04',
        selectedFacilityName: 'Apex Veterinary Trauma Care',
        status: CaseStatus.underTreatment,
        reporterName: 'Rajesh K',
        reporterPhone: '+91 98765 00009',
        imageUrl: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=800&q=80',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        estimatedCost: 9500.0,
        pawcareSupport: 6000.0,
        donorSupport: 2500.0,
        remainingCost: 1000.0,
        medicalNotes: ['Isolation unit ward admitted.', 'Intravenous fluids ongoing.'],
      ),
    ];
  }

  static List<FundingRequest> getInitialFundingRequests() {
    return [
      FundingRequest(
        id: 'FR-801',
        caseId: 'PC-2026-00124',
        animalName: 'Bruno (Indie Dog)',
        animalImageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80',
        volunteerName: 'Harsshith Saravanan',
        hospitalName: 'Paws Veterinary Specialty Hospital',
        diagnosis: 'Fractured Right Femur & Soft Tissue Trauma',
        treatmentDetails: 'Orthopedic surgery, titanium pin insertion, 5-day post-op ICU care & antibiotics.',
        estimatedCost: 8000.0,
        pawcareSupport: 5000.0,
        donorSupport: 2000.0,
        remainingAmount: 1000.0,
      ),
      FundingRequest(
        id: 'FR-802',
        caseId: 'PC-2026-00122',
        animalName: 'Rocky (Senior Dog)',
        animalImageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
        volunteerName: 'Karthik Raja',
        hospitalName: 'Hope Animal Rescue Shelter',
        diagnosis: 'Severe Demodectic Mange & Malnutrition',
        treatmentDetails: 'Medicated bath protocol, Ivermectin therapy, specialized high-calorie protein diet.',
        estimatedCost: 6000.0,
        pawcareSupport: 4000.0,
        donorSupport: 1500.0,
        remainingAmount: 500.0,
      ),
      FundingRequest(
        id: 'FR-803',
        caseId: 'PC-2026-00115',
        animalName: 'Leo (Puppy)',
        animalImageUrl: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=800&q=80',
        volunteerName: 'Rajesh K',
        hospitalName: 'Apex Veterinary Trauma Care',
        diagnosis: 'Canine Parvovirus Severe Dehydration',
        treatmentDetails: 'Isolation ICU care, IV fluids, anti-emetics, plasma support.',
        estimatedCost: 9500.0,
        pawcareSupport: 6000.0,
        donorSupport: 2500.0,
        remainingAmount: 1000.0,
      ),
      FundingRequest(
        id: 'FR-804',
        caseId: 'PC-2026-00123',
        animalName: 'Milo (Kitten)',
        animalImageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
        volunteerName: 'Priya Sharma',
        hospitalName: 'CareVet Clinic & Diagnostic Centre',
        diagnosis: 'Lacerated Paw Pad & Sepsis Risk',
        treatmentDetails: 'Laceration repair, antiseptic dressing, tetanus shot, oral antibiotics.',
        estimatedCost: 3500.0,
        pawcareSupport: 2500.0,
        donorSupport: 1000.0,
        remainingAmount: 0.0,
      ),
      FundingRequest(
        id: 'FR-805',
        caseId: 'PC-2026-00120',
        animalName: 'Tommy (Indie Dog)',
        animalImageUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=800&q=80',
        volunteerName: 'Suresh Kumar',
        hospitalName: 'Apex Veterinary Trauma Care',
        diagnosis: 'Tail Barbed Wire Cut Injury',
        treatmentDetails: 'Tail amputation tips, suturing, pain management injections.',
        estimatedCost: 3000.0,
        pawcareSupport: 2000.0,
        donorSupport: 1000.0,
        remainingAmount: 0.0,
      ),
    ];
  }

  static List<Donation> getInitialDonations() {
    return [
      Donation(
        id: 'DON-101',
        transactionId: 'TXN-998124',
        caseId: 'PC-2026-00124',
        caseTitle: 'Bruno (Indie Dog Treatment)',
        donorName: 'Harsshith Saravanan',
        amount: 1000.0,
        date: DateTime.now().subtract(const Duration(hours: 2)),
        category: 'Emergency Treatment',
      ),
      Donation(
        id: 'DON-102',
        transactionId: 'TXN-998125',
        caseId: 'PC-2026-00122',
        caseTitle: 'Rocky (Mange Treatment)',
        donorName: 'Anil Kumar',
        amount: 500.0,
        date: DateTime.now().subtract(const Duration(days: 1)),
        category: 'Emergency Treatment',
      ),
      Donation(
        id: 'DON-103',
        transactionId: 'TXN-998126',
        caseTitle: 'General AnimalConnect Animal Care Fund',
        donorName: 'Anonymous Supporter',
        amount: 2500.0,
        date: DateTime.now().subtract(const Duration(days: 2)),
        category: 'General Animal Care',
      ),
      Donation(
        id: 'DON-104',
        transactionId: 'TXN-998127',
        caseId: 'PC-2026-00121',
        caseTitle: 'Puppy Litter Medicine & Vaccines',
        donorName: 'Dr. Lakshmi Prasanna',
        amount: 1500.0,
        date: DateTime.now().subtract(const Duration(days: 3)),
        category: 'Medicine Support',
      ),
      Donation(
        id: 'DON-105',
        transactionId: 'TXN-998128',
        caseTitle: 'Hope Animal Shelter Feeding Drive',
        donorName: 'Coimbatore Pet Lovers Club',
        amount: 5000.0,
        date: DateTime.now().subtract(const Duration(days: 5)),
        category: 'Shelter Care',
      ),
    ];
  }

  static List<MedicineItem> getInitialMedicines() {
    return [
      MedicineItem(
        id: 'med-01',
        name: 'VetHeal Antiseptic Wound Spray (150ml)',
        category: 'Wound Care',
        price: 280.0,
        isPrescriptionRequired: false,
        providerName: 'Paws MedExpress Delivery',
        description: 'Fast-acting topical spray for maggots, cuts, and open animal wounds.',
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
      ),
      MedicineItem(
        id: 'med-02',
        name: 'Cephavet 300mg Antibiotic Tablets (10s)',
        category: 'Prescription',
        price: 420.0,
        isPrescriptionRequired: true,
        providerName: 'Paws MedExpress Delivery',
        description: 'Broad-spectrum cephalexin antibiotic for canine skin and soft tissue infections.',
        imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=80',
      ),
      MedicineItem(
        id: 'med-03',
        name: 'NutriPaw Calcium & Multi-Vitamin Syrup (200ml)',
        category: 'Supplements',
        price: 310.0,
        isPrescriptionRequired: false,
        providerName: 'VetCare Pharmacy',
        description: 'Essential vitamins and calcium supplement for growing puppies and recovering stray dogs.',
        imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=800&q=80',
      ),
      MedicineItem(
        id: 'med-04',
        name: 'Melonex Pain Relief Injectable/Oral Suspension',
        category: 'Prescription',
        price: 195.0,
        isPrescriptionRequired: true,
        providerName: 'Apex Veterinary Supplies',
        description: 'Meloxicam non-steroidal anti-inflammatory for acute trauma pain relief.',
        imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=800&q=80',
      ),
      MedicineItem(
        id: 'med-05',
        name: 'PawAid Emergency First-Aid Animal Kit',
        category: 'First Aid',
        price: 750.0,
        isPrescriptionRequired: false,
        providerName: 'Paws MedExpress Delivery',
        description: 'Includes sterile gauze, self-adhesive bandage, iodine solution, scissors, gloves & thermometer.',
        imageUrl: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=800&q=80',
      ),
    ];
  }

  static List<MedicineOrder> getInitialMedicineOrders() {
    return [
      MedicineOrder(
        id: 'ORD-701',
        orderId: 'PC-MED-9941',
        caseId: 'PC-2026-00124',
        items: [
          MedicineItem(
            id: 'med-02',
            name: 'Cephavet 300mg Antibiotic Tablets (10s)',
            category: 'Prescription',
            price: 420.0,
            isPrescriptionRequired: true,
            providerName: 'Paws MedExpress Delivery',
            description: 'Broad spectrum antibiotic.',
            imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=80',
          ),
          MedicineItem(
            id: 'med-01',
            name: 'VetHeal Antiseptic Wound Spray',
            category: 'Wound Care',
            price: 280.0,
            isPrescriptionRequired: false,
            providerName: 'Paws MedExpress Delivery',
            description: 'Topical spray.',
            imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
          ),
        ],
        deliveryAddress: 'Paws Veterinary Hospital, Avinashi Road, Peelamedu, Coimbatore',
        prescriptionUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
        status: MedicineOrderStatus.outForDelivery,
        orderDate: DateTime.now().subtract(const Duration(hours: 1)),
        totalPrice: 700.0,
      ),
      MedicineOrder(
        id: 'ORD-702',
        orderId: 'PC-MED-9940',
        caseId: 'PC-2026-00122',
        items: [
          MedicineItem(
            id: 'med-03',
            name: 'NutriPaw Multi-Vitamin Syrup',
            category: 'Supplements',
            price: 310.0,
            isPrescriptionRequired: false,
            providerName: 'VetCare Pharmacy',
            description: 'Multi-vitamin syrup.',
            imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=800&q=80',
          ),
        ],
        deliveryAddress: 'Hope Animal Shelter, Singanallur, Coimbatore',
        prescriptionUrl: '',
        status: MedicineOrderStatus.delivered,
        orderDate: DateTime.now().subtract(const Duration(days: 1)),
        totalPrice: 310.0,
      ),
      MedicineOrder(
        id: 'ORD-703',
        orderId: 'PC-MED-9939',
        caseId: 'PC-2026-00121',
        items: [
          MedicineItem(
            id: 'med-05',
            name: 'PawAid Emergency First-Aid Kit',
            category: 'First Aid',
            price: 750.0,
            isPrescriptionRequired: false,
            providerName: 'Paws MedExpress Delivery',
            description: 'First aid kit.',
            imageUrl: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=800&q=80',
          ),
        ],
        deliveryAddress: 'Saibaba Colony, Coimbatore',
        prescriptionUrl: '',
        status: MedicineOrderStatus.verified,
        orderDate: DateTime.now().subtract(const Duration(hours: 3)),
        totalPrice: 750.0,
      ),
      MedicineOrder(
        id: 'ORD-704',
        orderId: 'PC-MED-9938',
        items: [
          MedicineItem(
            id: 'med-01',
            name: 'VetHeal Antiseptic Spray',
            category: 'Wound Care',
            price: 280.0,
            isPrescriptionRequired: false,
            providerName: 'Paws MedExpress Delivery',
            description: 'Antiseptic spray.',
            imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
          ),
        ],
        deliveryAddress: 'PN Road, Tiruppur',
        prescriptionUrl: '',
        status: MedicineOrderStatus.delivered,
        orderDate: DateTime.now().subtract(const Duration(days: 3)),
        totalPrice: 280.0,
      ),
      MedicineOrder(
        id: 'ORD-705',
        orderId: 'PC-MED-9937',
        items: [
          MedicineItem(
            id: 'med-04',
            name: 'Melonex Pain Relief',
            category: 'Prescription',
            price: 195.0,
            isPrescriptionRequired: true,
            providerName: 'Apex Veterinary Supplies',
            description: 'Pain relief.',
            imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=800&q=80',
          ),
        ],
        deliveryAddress: 'Junction Road, Salem',
        prescriptionUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
        status: MedicineOrderStatus.preparing,
        orderDate: DateTime.now().subtract(const Duration(hours: 5)),
        totalPrice: 195.0,
      ),
    ];
  }

  static List<PetCareProvider> getInitialPetCareProviders() {
    return [
      PetCareProvider(
        id: 'pcp-01',
        name: 'HappyPaws Luxury Pet Boarding & Resort',
        serviceType: 'Pet Boarding',
        rating: 4.9,
        pricePerDay: 600.0,
        location: 'Saravanampatti, Coimbatore',
        isVerified: true,
        availabilityStatus: 'Available',
        imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&q=80',
        description: 'Air-conditioned rooms, CCTV monitoring, play area, and vet on-call for pets.',
        phone: '+91 98765 88001',
      ),
      PetCareProvider(
        id: 'pcp-02',
        name: 'Sniffers Professional Grooming Studio',
        serviceType: 'Grooming',
        rating: 4.8,
        pricePerDay: 800.0,
        location: 'Race Course, Coimbatore',
        isVerified: true,
        availabilityStatus: 'Available',
        imageUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=800&q=80',
        description: 'Full medicated bath, fur styling, nail clipping, and ear cleaning by certified groomers.',
        phone: '+91 98765 88002',
      ),
      PetCareProvider(
        id: 'pcp-03',
        name: 'Compassionate Community Foster Care',
        serviceType: 'Foster Care',
        rating: 4.9,
        pricePerDay: 0.0, // Volunteer foster
        location: 'Peelamedu, Coimbatore',
        isVerified: true,
        availabilityStatus: 'Available',
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=800&q=80',
        description: 'Verified home foster network for recovering post-surgery animals and rescued puppies.',
        phone: '+91 98765 88003',
      ),
      PetCareProvider(
        id: 'pcp-04',
        name: 'Wagging Tails Daily Pet Walking Service',
        serviceType: 'Pet Walking',
        rating: 4.7,
        pricePerDay: 250.0,
        location: 'RS Puram, Coimbatore',
        isVerified: true,
        availabilityStatus: 'Available',
        imageUrl: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=800&q=80',
        description: 'Experienced dog walkers with GPS track updates and behavioral exercise training.',
        phone: '+91 98765 88004',
      ),
      PetCareProvider(
        id: 'pcp-05',
        name: 'Coimbatore Paws & Tails Daycare',
        serviceType: 'Pet Boarding',
        rating: 4.6,
        pricePerDay: 450.0,
        location: 'Thudiyalur, Coimbatore',
        isVerified: true,
        availabilityStatus: 'Fully Booked',
        imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80',
        description: 'Spacious outdoor lawn and socialization zone for friendly dogs.',
        phone: '+91 98765 88005',
      ),
    ];
  }

  static List<AdoptionAnimal> getInitialAdoptionAnimals() {
    return [
      AdoptionAnimal(
        id: 'adopt-01',
        name: 'Charlie',
        animalType: 'Dog',
        breed: 'Indian Pariah (Indie)',
        age: '4 Months',
        gender: 'Male',
        isVaccinated: true,
        isSterilized: false,
        location: 'Hope Shelter, Coimbatore',
        shelterName: 'Hope Animal Rescue Shelter',
        shelterId: 'fac-02',
        story: 'Charlie was rescued during monsoon rains near Singanallur lake. He is full of energy, loves playing fetch, and gets along wonderfully with children and cats.',
        personality: ['Playful', 'Affectionate', 'Smart', 'Good with kids'],
        healthSummary: 'Fully vaccinated (DHPPi + Rabies), de-wormed, clear blood panel.',
        imageUrl: 'https://images.unsplash.com/photo-1591160690555-5debfba289f0?auto=format&fit=crop&w=800&q=80',
      ),
      AdoptionAnimal(
        id: 'adopt-02',
        name: 'Bella',
        animalType: 'Cat',
        breed: 'Domestic Short Hair (Indie)',
        age: '1 Year',
        gender: 'Female',
        isVaccinated: true,
        isSterilized: true,
        location: 'Blue Cross Shelter, Chennai',
        shelterName: 'Blue Cross Veterinary Hospital',
        shelterId: 'fac-06',
        story: 'Bella is a calm, gentle cat who loves warm sunny spots and purrs softly when brushed. Ideal for apartment living.',
        personality: ['Calm', 'Gentle', 'Litter Trained', 'Indoor Pet'],
        healthSummary: 'Spayed, fully vaccinated, FIV/FeLV negative.',
        imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
      ),
      AdoptionAnimal(
        id: 'adopt-03',
        name: 'Leo & Simba (Pair)',
        animalType: 'Dog',
        breed: 'Indie Puppy Duo',
        age: '3 Months',
        gender: 'Males',
        isVaccinated: true,
        isSterilized: false,
        location: 'Hope Shelter, Coimbatore',
        shelterName: 'Hope Animal Rescue Shelter',
        shelterId: 'fac-02',
        story: 'Rescued together from Saibaba Colony. Unbreakable bond between the brothers. Looking for a loving home together or separately.',
        personality: ['Energetic', 'Loyal', 'Friendly'],
        healthSummary: 'First dose vaccines administered, de-wormed.',
        imageUrl: 'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?auto=format&fit=crop&w=800&q=80',
      ),
      AdoptionAnimal(
        id: 'adopt-04',
        name: 'Luna',
        animalType: 'Cat',
        breed: 'Calico Cat',
        age: '2 Years',
        gender: 'Female',
        isVaccinated: true,
        isSterilized: true,
        location: 'Karuna Shelter, Tiruppur',
        shelterName: 'Karuna Animal Protection Shelter',
        shelterId: 'fac-05',
        story: 'Luna was rehabilitated from a mild paw injury. Now fully recovered and looking for a quiet home.',
        personality: ['Quiet', 'Loving', 'Clean'],
        healthSummary: 'Vaccinated and spayed.',
        imageUrl: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80',
      ),
      AdoptionAnimal(
        id: 'adopt-05',
        name: 'Rocky',
        animalType: 'Dog',
        breed: 'Labrador Mix',
        age: '2.5 Years',
        gender: 'Male',
        isVaccinated: true,
        isSterilized: true,
        location: 'Salem Sanctuary, Salem',
        shelterName: 'Salem Animal Welfare Sanctuary',
        shelterId: 'fac-08',
        story: 'Rocky is a gentle giant who loves walking and car rides. Fully house trained.',
        personality: ['Gentle', 'Trained', 'Active'],
        healthSummary: 'Sterilized, microchipped, fully vaccinated.',
        imageUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=800&q=80',
      ),
      AdoptionAnimal(
        id: 'adopt-06',
        name: 'Mimi',
        animalType: 'Cat',
        breed: 'Tabby Kitten',
        age: '5 Months',
        gender: 'Female',
        isVaccinated: true,
        isSterilized: false,
        location: 'Hope Shelter, Coimbatore',
        shelterName: 'Hope Animal Rescue Shelter',
        shelterId: 'fac-02',
        story: 'Sweet little kitten with inquisitive green eyes. Very playful.',
        personality: ['Curious', 'Playful'],
        healthSummary: 'Vaccinated and parasite free.',
        imageUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80',
      ),
      AdoptionAnimal(
        id: 'adopt-07',
        name: 'Bruno',
        animalType: 'Dog',
        breed: 'Indie Adult Dog',
        age: '3 Years',
        gender: 'Male',
        isVaccinated: true,
        isSterilized: true,
        location: 'Paws Hospital, Coimbatore',
        shelterName: 'Paws Veterinary Specialty Hospital',
        shelterId: 'fac-01',
        story: 'Completed leg injury treatment under AnimalConnect support. Fully healed, active and looking for a permanent family.',
        personality: ['Brave', 'Protective', 'Loyal'],
        healthSummary: 'Orthopedic treatment complete. Excellent recovery.',
        imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80',
      ),
      AdoptionAnimal(
        id: 'adopt-08',
        name: 'Daisy',
        animalType: 'Other',
        breed: 'Rescue Rabbit',
        age: '1 Year',
        gender: 'Female',
        isVaccinated: true,
        isSterilized: true,
        location: 'Karuna Shelter, Tiruppur',
        shelterName: 'Karuna Animal Protection Shelter',
        shelterId: 'fac-05',
        story: 'Rescued rabbit, gentle demeanor, litter trained and loves fresh greens.',
        personality: ['Gentle', 'Quiet'],
        healthSummary: 'Health checked by exotics veterinarian.',
        imageUrl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=800&q=80',
      ),
    ];
  }

  static List<AppNotification> getInitialNotifications() {
    return [
      AppNotification(
        id: 'notif-01',
        title: 'Case Admitted at Paws Hospital',
        body: 'Case PC-2026-00124 (Bruno) has been admitted for emergency treatment.',
        timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
        isRead: false,
        category: 'Case',
        caseId: 'PC-2026-00124',
      ),
      AppNotification(
        id: 'notif-02',
        title: 'AnimalConnect Treatment Fund Approved',
        body: 'Funding request FR-801 verified! ₹5,000 AnimalConnect Support allocated.',
        timestamp: DateTime.now().subtract(const Duration(hours: 2)),
        isRead: false,
        category: 'Funding',
        caseId: 'PC-2026-00124',
      ),
      AppNotification(
        id: 'notif-03',
        title: 'New Donation Received!',
        body: 'Your donation of ₹1,000 for Bruno treatment support was confirmed. Receipt TXN-998124 generated.',
        timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)),
        isRead: true,
        category: 'Donation',
      ),
      AppNotification(
        id: 'notif-04',
        title: 'Medicine Order Out for Delivery',
        body: 'Prescription order PC-MED-9941 is out for delivery to Paws Hospital.',
        timestamp: DateTime.now().subtract(const Duration(hours: 1)),
        isRead: false,
        category: 'General',
      ),
      AppNotification(
        id: 'notif-05',
        title: 'Adoption Application Under Review',
        body: 'Hope Shelter is reviewing your application for Charlie (Adoption ID AD-2026-09).',
        timestamp: DateTime.now().subtract(const Duration(days: 1)),
        isRead: true,
        category: 'Adoption',
      ),
      AppNotification(
        id: 'notif-06',
        title: 'Treatment Completed',
        body: 'Case PC-2026-00120 (Tommy) treatment is complete. Ready for shelter recovery.',
        timestamp: DateTime.now().subtract(const Duration(days: 3)),
        isRead: true,
        category: 'Case',
        caseId: 'PC-2026-00120',
      ),
      AppNotification(
        id: 'notif-07',
        title: 'New Nearby Animal Case Reported',
        body: 'Injured cat reported 2.4 km near Ramanathapuram. Volunteer support requested.',
        timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
        isRead: true,
        category: 'Case',
      ),
      AppNotification(
        id: 'notif-08',
        title: 'Facility Verification Certificate Updated',
        body: 'Apex Veterinary Trauma Care (Tiruppur) verification renewed for 2026.',
        timestamp: DateTime.now().subtract(const Duration(days: 4)),
        isRead: true,
        category: 'General',
      ),
      AppNotification(
        id: 'notif-09',
        title: 'Volunteer Status Active',
        body: 'Welcome Harsshith! You are an Active AnimalConnect Rescue Volunteer.',
        timestamp: DateTime.now().subtract(const Duration(days: 10)),
        isRead: true,
        category: 'General',
      ),
      AppNotification(
        id: 'notif-10',
        title: 'Monthly Animal Welfare Report',
        body: '1,280+ animals helped in your region this month. Thank you for your support!',
        timestamp: DateTime.now().subtract(const Duration(days: 12)),
        isRead: true,
        category: 'General',
      ),
    ];
  }
}
